---
- name: Deploy Fedora Workstation
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars/dotfiles.yml
    - vars/hostvars.yml

  tasks:
    - name: Fedora Tasks
      import_tasks: tasks/fedora.yml

    - name: Dnsmasq tasks
      import_tasks: tasks/dnsmasq.yml
      become: true

    - name: Virtualization tasks
      import_tasks: tasks/virt.yml
      become: true

    - name: Docker tasks
      import_tasks: tasks/docker.yml
      become: true

    - name: Dotfiles Tasks
      import_tasks: tasks/dotfiles.yml

    - name: Vim Configs
      import_tasks: tasks/vim.yml

  handlers:
    - name: Handlers
      import_tasks: handlers/handlers.yml
    # - name: primeiro teste debug
    #   debug:
    #     msg: chamado com sucesso
