---
- name: Deploy Macos
  hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - vars/dotfiles.yml

  tasks:
    - name: inclui lista de pacotes de acordo com o SO obtido pelo ansible
      include_vars: "vars/packages{{ ansible_system }}.yml"

    - name: Macos Tasks
      import_tasks: tasks/darwin.yml

    - name: Dotfiles Tasks
      import_tasks: tasks/dotfiles.yml

    - name: Vim Configs
      import_tasks: tasks/vim.yml
