---
- name: Deploy Fedora Workstation
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    - githubuser: nnorakk@gmail.com
    - fedoraversion: 31

  # vars_prompt:
  #   - name: githubpassword
  #     prompt: "Digite a senha github"
  #     private: yes

  tasks:
    - name: inclui lista de pacotes de acordo com o SO obtido pelo ansible
      include_vars: "vars/packages{{ ansible_system }}.yml"

    - name: Tarefas Fedora
      import_tasks: tasks/fedora.yml

    # Verificar destino depois colocar variavel do homeuser
    - name: clone repositorio dotfiles do github
      git:
        repo: https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/nnorakk/dotfilesCasa
        dest: $HOME/.my-dotfiles 
        bare: yes
        update: yes
      tags: dotfiles

    - name: Clona repostiorio fzf
      git:
        repo: https://github.com/junegunn/fzf
        dest: $HOME/.fzf
      tags: dotfiles, fzf

    - name: Instala oh-my-zsh
      git: 
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: $HOME/.oh-my-zsh
      tags: dotfiles, zsh

    - name: Instala zsh-autosuggestions
      git: 
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: $HOME/.oh-my-zsh/plugins/zsh-autosuggestions
      tags: dotfiles, zsh

    - name: Instala Tmux themes
      git: 
        repo: https://github.com/jimeh/tmux-themepack.git
        dest: $HOME/.tmux-themepack
      tags: dotfiles, tmux

    - name: recupera todos os arquivos do repositorio
      command:
        cmd: git --git-dir=$HOME/.my-dotfiles/ --work-tree=$HOME {{ item }} 
      with_items:
        - pull origin master
        - checkout -f
      tags: dotfiles

    - name: clone repositorio gerenciador de plugins vundle
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: ~/.vim/bundle/Vundle.vim
        update: yes
      tags: vim

    - name: Instala plugins vim
      command:
        cmd: vim +PluginInstall +qall
      tags: vim

    - name: Finaliza instalacao YouCompleteMe plugin vim
      command:
        cmd: ~/.vim/bundle/YouCompleteMe/install.py
      tags: vim

    # para usar o dropbox com muitos arquivos:
    # echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p

    # - name: primeiro teste debug
    #   debug:
    #     msg: chamado com sucesso
