---
- name: Deploy Fedora Workstation
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars/dotfiles.yml

  pre_tasks:
    - name: Inclui arquivo de variaveis hostvars caso exista
      include_vars:
        file: "vars/hostvars.yml"
      ignore_errors: yes
      failed_when: false

  tasks:
    - name: Fedora Tasks
      import_tasks: tasks/fedora.yml

    - name: Keyboard Tasks
      import_tasks: tasks/keyboard.yml

    - name: Dnsmasq tasks
      import_tasks: tasks/dnsmasq.yml
      become: true

    - name: Dotfiles Tasks
      import_tasks: tasks/dotfiles.yml

    - name: Vim Configs
      import_tasks: tasks/vim.yml

  roles:
    - { role: kvm, tags: ["kvm"] }
    - { role: docker, tags: ["docker"] }
    - { role: compiled_apps, tags: ["compiled_apps"] }

  handlers:
    - name: Handlers
      import_tasks: handlers/handlers.yml
