---
- name: Deploy Fedora Workstation
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    - githubuser: nnorakk@gmail.com
    - fedoraversion: 31

  vars_files:
    - vars/dotfiles.yml
  # vars_prompt:
  #   - name: githubpassword
  #     prompt: "Digite a senha github"
  #     private: yes

  tasks:
    - name: inclui lista de pacotes de acordo com o SO obtido pelo ansible
      include_vars: "vars/packages{{ ansible_system }}.yml"

    - name: Fedora Tasks
      import_tasks: tasks/fedora.yml

    - name: Dotfiles Tasks
      import_tasks: tasks/dotfiles.yml

    - name: Vim Configs
      import_tasks: tasks/vim.yml


    # para usar o dropbox com muitos arquivos:
    # echo fs.inotify.max_user_watches=100000 | sudo tee -a /etc/sysctl.conf; sudo sysctl -p

    # - name: primeiro teste debug
    #   debug:
    #     msg: chamado com sucesso
