---
- name: Verifica se vm ou host fisico
  shell:
    cmd: dmesg | grep 'Hypervisor detected:'
  register: is_vm
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: Inclui variaveis para distribuicao especifica
  include_vars: "{{ ansible_distribution }}.yml"

- name: Inclui tarefa de instalacao de pacotes para distribuicao especifica
  include_tasks: "task_{{ ansible_distribution }}.yml"

- name: Adiciona usuario ao grupo libvirt
  user:
    name: "{{ lookup('env','LOGNAME') }}"
    groups: libvirt
    append: yes
  when: kvm_packages is defined
  become: true
