#!/usr/bin/sh

# clean bspwm rules
bspc rule -r "*"

# define monitores
export monitor1=$(xrandr --listmonitors | awk '/0:/{ print $4}')
export monitor2=$(xrandr --listmonitors | awk '/1:/{ print $4}')

# seta manualmente resolucao 
if [[ $(hostname) == bluestar* ]]; then 
    xrandr --newmode resolucao  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync; 
    xrandr --addmode ${monitor1} resolucao; 
    xrandr --output ${monitor1} --mode resolucao

    # Define 10 Desktops
    bspc monitor ${monitor1} -d 1 2 3 4 5 6 7 8
else
    # Define 8 Desktops em 2 monitores
    bspc monitor ${monitor1} -d 1 2 3 4
    bspc monitor ${monitor2} -d 5 6 7 8
fi

# configs
bspc config window_gap 4
bspc config top_padding 29
bspc config border_width 4
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# adicionada essa configuracao porque a rule do zoiper ignorava o focus,follow=off
# fonte: https://www.reddit.com/r/bspwm/comments/fclm60/window_is_focused_even_though_focusoff/
bspc config ignore_ewmh_focus    true

# mouse settings
# com a tecla Alt pressionada move float window usando mouse
bspc config pointer_modifier mod1
# botao direito move a janela
bspc config pointer_action1 move
# botao central redimensiona janela usando a lateral mais proxima
bspc config pointer_action2 resize_side
# botao esquerdo redimensiona janela usando o corner
bspc config pointer_action3 resize_corner
# bspc config click_to_focus none

# Cores
bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color "#5e81ac"
# bspc config external_rules_command /home/jpaulo/.config/bspwm/external_rules

# Rules
bspc rule -a vlc state=fullscreen
bspc rule -a xfreerdp desktop='^8' state=floating follow=on center=true
bspc rule -a "Gnome-calculator" state=floating follow=on
# bspc rule ^7 --layout monocle
bspc rule -a "org.remmina.Remmina" desktop='^7' state=monocle follow=on
bspc rule -a Bashtop state=floating follow=on
bspc rule -a Ranger state=floating follow=on
bspc rule -a Calendar state=floating rectangle=680x770+540+110 layer=above
bspc rule -a Fzfsearch state=floating rectangle=680x770+540+110 layer=above
bspc rule -a Zathura state=floating rectangle=680x770+540+110 layer=above
bspc rule -a Zoiper5 desktop='^7' state=floating follow=off
bspc rule -a "serpro-ppgd-app-IRPFPGD" state=floating follow=on

# inicia sxhkd caso nao esteja rodando
pgrep -x sxhkd > /dev/null || sxhkd -m 1 &

# Inicia polybar caso nao esteja rodando
pgrep -x polybar > /dev/null || ${HOME}/.config/polybar/launch.sh

# Start Dropbox
dropbox start

# Random Wallpaper
feh --bg-fill --randomize ${HOME}/tmp/bspwm-wallpapers/backgrounds/*

# seta formato cursor mouse
xsetroot -cursor_name left_ptr

# esconde cursor do mouse
pgrep -x unclutter > /dev/null || unclutter & 

# Inicia compositor
pgrep -x picom > /dev/null || picom &
bspc config top_padding 29

# Inicia Notificacoes
pgrep -x dunst > /dev/null || dunst &

# protege tela depois de 5 minutos
pgrep -x xautolock > /dev/null || xautolock -time 5 -locker 'betterlockscreen -l; betterlockscreen -u  ~/tmp/bspwm-wallpapers/backgrounds' -notify 30 -notifier "notify-send -u critical -t 10000 'Locking screen in 30 seconds'" &

# abre terminal kitty
pgrep -x kitty > /dev/null || kitty &

# nm-applet --indicator &
nm-applet --indicator &

# automount disks
udiskie &
