#!/usr/bin/sh

# clean bspwm rules
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd -m 1 &

# seta manualmente resolucao 
xrandr --newmode resolucao  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync; 
xrandr --addmode HDMI-1 resolucao; 
xrandr --output HDMI-1 --mode resolucao

bspc monitor -d I II III IV V VI VII VIII IX X

# pgrep -x polybar > /dev/null || polybar example &
pgrep -x polybar > /dev/null || ${HOME}/.config/polybar/launch.sh

pgrep -x kitty > /dev/null || kitty &

bspc config window_gap 4
bspc config top_padding 4
bspc config border_width 4

bspc config split_ratio          0.52
# bspc config borderless_monocle   true
bspc config gapless_monocle      true

# mouse settings
# com a tecla Shift pressionada move float window usando mouse
bspc config pointer_modifier shift
# botao direito move a janela
bspc config pointer_action1 move
# botao central redimensiona janela usando a lateral mais proxima
bspc config pointer_action2 resize_side
# botao esquerdo redimensiona janela usando o corner
bspc config pointer_action3 resize_corner
# bspc config click_to_focus none


# Cores copiadas
bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#406ea5"
bspc config presel_feedback_color "#5e81ac"
# bspc config urgent_border_color "#dd2727"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# abre vlc em fullscreen
bspc rule -a vlc state=fullscreen
bspc rule -a xfreerdp desktop='^8' state=floating follow=on
# nao funcionando, investigar depois rules bspc
# https://github.com/baskerville/bspwm/issues/291
# https://github.com/D630/bin/blob/master/bspwm-rules
bspc rule -a Spotify desktop='^8' state=floating follow=on
bspc rule -a Zoiper5 desktop='^8' state=floating follow=on
# bspc rule -a snap desktop='^8' state=floating follow=on

# Start Dropbox
dropbox start

# Random Wallpaper
feh --bg-fill --randomize ${HOME}/tmp/bspwm-wallpapers/backgrounds/*

# ajuste do teclado
# capslock funciona como Control quando pressionada com outra tecla
setxkbmap -option ctrl:nocaps
# scrollock funciona como CapsLock
xmodmap -e "keycode 78 = Caps_Lock NoSymbol Caps_Lock"
# CapsLock funciona como backspace quando pressionada e liberada
${HOME}/tmp/xcape/xcape -e 'Control_L=BackSpace' && killall xcape && ${HOME}/tmp/xcape/xcape -e 'Control_L=BackSpace'

# xmodmap -pke > ~/xmodmap_durante_bspwmrc
# xmodmap xmodmap_original
# xmodmap xmodmapteste
# tmp/xcape/xcape -e 'Control_R=BackSpace'

# Inicia compositor
# pgrep -x picom > /dev/null || picom &

# Inicia Notificacoes
pgrep -x dunst > /dev/null || dunst &

# protege tela depois de 5 minutos
pgrep -x xautolock > /dev/null || xautolock -time 5 -locker 'betterlockscreen -l; betterlockscreen -u  ~/tmp/bspwm-wallpapers/backgrounds' 
