syntax on " habilita syntax highlight

set clipboard=unnamed,unnamedplus " forca usar registros * e + em yank

set background=dark " seta tema para dark

set backspace=indent,eol,start " comportamento backspace

set foldmethod=indent " Usa folding atraves da identacao
set foldlevel=99 " Abre sem folding

" leader map igual a espaco. Default e '\'
let mapleader = "\ "

" expande tabs em espaco
set tabstop=4 softtabstop=4 shiftwidth=4 expandtab

" ignore case em buscas /
set ignorecase smartcase

" permite usar 24-bit colors, permite usar colorscheme do plugin base16 
" set termguicolors
if exists('+termguicolors')
    " correcao quando usa dentro do tmux
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
    set termguicolors
endif

" Permite redimensionar window dentro do tmux
if !has('nvim')
    set ttymouse=sgr
endif

" Seta line e relativenumber
set number relativenumber

" Habilita highlight na linha atual
set cursorline

" Modifica o caracter separador vertical (U+2503, UTF-8: E2 94 83)
set fillchars+=vert:┃

" Preferencias ao splitar janelas
set splitbelow splitright

" Remove a mensagem de Intro do vim 
set shortmess+=I

" Permite saltar para buffers nao salvos
set hidden

" Nao imprime comando na ultima linha
set noshowcmd

" gerenciador de plugins vim-plug
" https://github.com/junegunn/vim-plug
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-commentary' " comments using 'gc'
Plug 'tpope/vim-surround' " surround comandos ysw',csw',ds...
Plug 'tpope/vim-fugitive' " Plugin Git
Plug 'tpope/vim-repeat' " permite usar o . ( dot ) para o plugin vim-surround
Plug 'itchyny/lightline.vim' " status line plugin bem minimalista
Plug 'w0rp/ale' " linter 
Plug 'mhinz/vim-signify' " Indica se houve mudanca da versao atual do arquivo no git
Plug 'itchyny/vim-gitbranch' " Captura BranchName para mostrar no statusline
Plug 'Yggdroot/indentLine' " identacao 
Plug 'christoomey/vim-tmux-navigator' " Transparente navegar entre vim windows e tmux panes
Plug 'junegunn/fzf.vim' " fzf fuzzy finder
Plug 'junegunn/fzf' " fzf com funcoes para plugin vim 
Plug 'wincent/terminus' " necessario para os eventos de focus{Gained,Lost} dentro do tmux
Plug 'simeji/winresizer' " redimensionar janela: inicia modo resize ctrl+e
" visualizacao
Plug 'morhetz/gruvbox' " Plugin colorscheme gruvbox
Plug 'blueyed/vim-diminactive' " destacar janela selecionada e esmaecer as nao selecionadas
								 " precisa setar o hi ColorColumn para ficar mais adequado
Plug 'chriskempson/base16-vim' " cores
" Syntax
Plug 'kovetskiy/sxhkd-vim' " syntax sxhkd file
Plug 'ap/vim-css-color' " Color name highlight
Plug 'hashivim/vim-terraform' " highlight arquivos terraform
Plug 'jvirtanen/vim-hcl' " highlight arquivos packer
" fern e icones
Plug 'lambdalisue/fern.vim' " tree viewer
Plug 'lambdalisue/nerdfont.vim' " Nerdfont fern
Plug 'lambdalisue/fern-renderer-nerdfont.vim' " Nerdfont fern renderer
Plug 'lambdalisue/glyph-palette.vim' " choose font
Plug 'ryanoasis/vim-devicons' " Icons 
" Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
if ! has('nvim') " Nao habilita se utilizar o neovim
    Plug 'ycm-core/YouCompleteMe', { 'do': './install.py' } " tem que instalar: 
                                    " sudo dnf install cmake gcc-c++ make
                                    " python3-devel
                                    " então entrar no diretorio e instalar:
                                    " install.py
end
call plug#end()

" Fern configuration render nerdfont
let g:fern#renderer = "nerdfont"
" let g:fern#disable_default_mappings = 1
" nmap <buffer> <CR> <Plug>(fern-my-open-expand-collapse)

" Fern change color
augroup my-glyph-palette
  autocmd! *
  autocmd FileType fern call glyph_palette#apply()
  autocmd FileType nerdtree,startify call glyph_palette#apply()
augroup END

" TODO: verificar configuracao dentro de virtualenv
" YouCompleteMe : Fechar janela quando concluir complete
let g:ycm_autoclose_preview_window_after_completion=1

" esmaecer quando muda de tmux pane
let g:diminactive_enable_focus = 1

" Ale : Comandos mais uteis :ALEToggle :ALEInfo :ALEFix
let g:ale_python_pylint_options = '--disable=C0103'
let g:ale_fix_on_save = 1
let g:ale_linters = {
      \ 'python': [
      \    'flake8', 
      \    'pylint'
      \    ]
      \}
let g:ale_fixers = {
						\ 'python': [
						\	'isort',
						\   'remove_trailing_lines',
						\   'yapf',
						\	'trim_whitespace',
						\   'add_blank_lines_for_python_control_statements'
						\	]
						\}

" indentline, nao mostra em text e help files
let g:indentLine_fileTypeExclude = ['text', 'help', 'vim', 'man']

" seta esquema de cores
" silent! color base16-default-dark " desert
silent! color gruvbox

" fzf layout
let g:fzf_layout = { 'window': { 'width': 0.8, 'height': 0.4 } }
let $FZF_DEFAULT_OPTS='--reverse'
" fzf action como abrir a selecao
let g:fzf_action = { 
            \'ctrl-t': 'tab split',
            \'ctrl-s': 'split',
            \'ctrl-x': 'split',
            \'ctrl-v': 'vsplit'
            \}

" desabilita relativenumber quando em modo insercao
augroup BgHighlight
	autocmd!
    autocmd WinEnter,InsertLeave,FocusGained * call change_numbering#set_relativenumber()
	autocmd WinLeave,BufLeave,InsertEnter,FocusLost * call change_numbering#unset_relativenumber()
	autocmd FocusLost * silent redraw!
	autocmd FocusGained * silent redraw!
augroup END
